//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1086 with alias "Abstractlink"
	/// <summary>AbstractLink</summary>
	public partial interface IAbstractlink : IPublishedContent
	{
		/// <summary>External Link</summary>
		string ExternalLink { get; }

		/// <summary>Internal Link</summary>
		string InternalLink { get; }
	}

	/// <summary>AbstractLink</summary>
	[PublishedContentModel("Abstractlink")]
	public partial class Abstractlink : PublishedContentModel, IAbstractlink
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Abstractlink";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Abstractlink(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Abstractlink, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// External Link: Optional link to an external page. External link always opens in a new window. External link OVERRIDES internal link in case it is also set.
		///</summary>
		[ImplementPropertyType("externalLink")]
		public string ExternalLink
		{
			get { return GetExternalLink(this); }
		}

		/// <summary>Static getter for External Link</summary>
		public static string GetExternalLink(IAbstractlink that) { return that.GetPropertyValue<string>("externalLink"); }

		///<summary>
		/// Internal Link: Link to a page on your site
		///</summary>
		[ImplementPropertyType("internalLink")]
		public string InternalLink
		{
			get { return GetInternalLink(this); }
		}

		/// <summary>Static getter for Internal Link</summary>
		public static string GetInternalLink(IAbstractlink that) { return that.GetPropertyValue<string>("internalLink"); }
	}
}
