//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1087 with alias "AbstractSocialLinks"
	/// <summary>AbstractSocialLinks</summary>
	public partial interface IAbstractSocialLinks : IPublishedContent
	{
		/// <summary>Behance</summary>
		string SocialBehance { get; }

		/// <summary>Facebook</summary>
		string SocialFacebook { get; }

		/// <summary>Flickr</summary>
		string SocialFlickr { get; }

		/// <summary>Google+</summary>
		string SocialGoogleplus { get; }

		/// <summary>Instagram</summary>
		string SocialInstagram { get; }

		/// <summary>LinkedIn</summary>
		string SocialLinkedin { get; }

		/// <summary>Tumblr</summary>
		string SocialTumblr { get; }

		/// <summary>Twitter</summary>
		string SocialTwitter { get; }

		/// <summary>Vimeo</summary>
		string SocialVimeo { get; }

		/// <summary>YouTube</summary>
		string SocialYoutube { get; }
	}

	/// <summary>AbstractSocialLinks</summary>
	[PublishedContentModel("AbstractSocialLinks")]
	public partial class AbstractSocialLinks : PublishedContentModel, IAbstractSocialLinks
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "AbstractSocialLinks";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AbstractSocialLinks(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AbstractSocialLinks, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Behance
		///</summary>
		[ImplementPropertyType("socialBehance")]
		public string SocialBehance
		{
			get { return GetSocialBehance(this); }
		}

		/// <summary>Static getter for Behance</summary>
		public static string GetSocialBehance(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialBehance"); }

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("socialFacebook")]
		public string SocialFacebook
		{
			get { return GetSocialFacebook(this); }
		}

		/// <summary>Static getter for Facebook</summary>
		public static string GetSocialFacebook(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialFacebook"); }

		///<summary>
		/// Flickr
		///</summary>
		[ImplementPropertyType("socialFlickr")]
		public string SocialFlickr
		{
			get { return GetSocialFlickr(this); }
		}

		/// <summary>Static getter for Flickr</summary>
		public static string GetSocialFlickr(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialFlickr"); }

		///<summary>
		/// Google+
		///</summary>
		[ImplementPropertyType("socialGoogleplus")]
		public string SocialGoogleplus
		{
			get { return GetSocialGoogleplus(this); }
		}

		/// <summary>Static getter for Google+</summary>
		public static string GetSocialGoogleplus(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialGoogleplus"); }

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("socialInstagram")]
		public string SocialInstagram
		{
			get { return GetSocialInstagram(this); }
		}

		/// <summary>Static getter for Instagram</summary>
		public static string GetSocialInstagram(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialInstagram"); }

		///<summary>
		/// LinkedIn
		///</summary>
		[ImplementPropertyType("socialLinkedin")]
		public string SocialLinkedin
		{
			get { return GetSocialLinkedin(this); }
		}

		/// <summary>Static getter for LinkedIn</summary>
		public static string GetSocialLinkedin(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialLinkedin"); }

		///<summary>
		/// Tumblr
		///</summary>
		[ImplementPropertyType("socialTumblr")]
		public string SocialTumblr
		{
			get { return GetSocialTumblr(this); }
		}

		/// <summary>Static getter for Tumblr</summary>
		public static string GetSocialTumblr(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialTumblr"); }

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("socialTwitter")]
		public string SocialTwitter
		{
			get { return GetSocialTwitter(this); }
		}

		/// <summary>Static getter for Twitter</summary>
		public static string GetSocialTwitter(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialTwitter"); }

		///<summary>
		/// Vimeo
		///</summary>
		[ImplementPropertyType("socialVimeo")]
		public string SocialVimeo
		{
			get { return GetSocialVimeo(this); }
		}

		/// <summary>Static getter for Vimeo</summary>
		public static string GetSocialVimeo(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialVimeo"); }

		///<summary>
		/// YouTube
		///</summary>
		[ImplementPropertyType("socialYoutube")]
		public string SocialYoutube
		{
			get { return GetSocialYoutube(this); }
		}

		/// <summary>Static getter for YouTube</summary>
		public static string GetSocialYoutube(IAbstractSocialLinks that) { return that.GetPropertyValue<string>("socialYoutube"); }
	}
}
