//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Info Section</summary>
	[PublishedContentModel("infoSection")]
	public partial class InfoSection : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "infoSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public InfoSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<InfoSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Facebook linkUrl: facebook link where user will redirect to on click. If filled, shows fb icon, If empty, no icon will display.
		///</summary>
		[ImplementPropertyType("facebookLinkUrl")]
		public string FacebookLinkUrl
		{
			get { return this.GetPropertyValue<string>("facebookLinkUrl"); }
		}

		///<summary>
		/// Image Url
		///</summary>
		[ImplementPropertyType("imageUrl")]
		public string ImageUrl
		{
			get { return this.GetPropertyValue<string>("imageUrl"); }
		}

		///<summary>
		/// Info text: write address (4 lines)
		///</summary>
		[ImplementPropertyType("infoText")]
		public string InfoText
		{
			get { return this.GetPropertyValue<string>("infoText"); }
		}

		///<summary>
		/// Youtube linkUrl: youtube link user will redirect to and will show youtube icon. If empty, no icon will display
		///</summary>
		[ImplementPropertyType("youtubeLinkUrl")]
		public string YoutubeLinkUrl
		{
			get { return this.GetPropertyValue<string>("youtubeLinkUrl"); }
		}
	}
}
